version: "3.8"

services:
  jdk8:
    build:
      context: ./docker/builds/jdk8
      dockerfile: Dockerfile
    volumes:
      - target:/var/www/java8-se-oracle-certified-associate
      - jvm-sources:/usr/local/openjdk-8
      - maven-repository:/root/.m2
    ports:
      - 5005:5005
    environment:
      - DEBUG=${DEBUG}
volumes:
  target:
    driver: local
    driver_opts:
      type: none
      device: ${CODEBASE}
      o: bind
  jvm-sources:
    driver: local
    driver_opts:
      type: none
      device: ${CODEBASE}/jvm-sources
      o: bind
  maven-repository:
    driver: local
    driver_opts:
      type: none
      device: ${CODEBASE}/.m2
      o: bind